import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { FaBell } from "react-icons/fa";
import { FaUserCircle } from "react-icons/fa";
import { IoSearch } from "react-icons/io5";
import Link from "next/link";
import { IoMdHelpCircle } from "react-icons/io";
import { HiPuzzle } from "react-icons/hi";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F8F9FA]`}
      >
        <div className="navColor text-white navbar p-2.5 fixed w-full z-20 drop-shadow-xl">
          <div className="header flex items-center space-x-8">
            <h1 className="font-bold text-xl">Homify</h1>
            <div className="flex items-center space-x-1">
              <input
                type="search"
                className="bg-white rounded-full text-black px-2 py-0.5 w-72"
                placeholder="Search New houses"
              />{" "}
              <button className="accentColor p-1.5 rounded-full cursor-pointer hover:scale-110 transition-all ease-in">
                <IoSearch className="text-[#1A1F71]" />
              </button>
            </div>
          </div>
          <div className="nav w-68">
            {/* <select value="Category" name="category">
              <option>Apartment</option>
              <option>Rent</option>
            </select> */}
            <button className="bg-white text-black px-4 py-1 rounded-full font-semibold flex items-center hover:bg-[#e3a900]">
              <FaBell className="text-[#1A1F71]" />
              <p className="ml-2 text-[#1A1F71]">Notification</p>
              <span></span>
            </button>
            <button className="border-2 border-dashed border-[#F4B400] text-[#F4B400] px-4 py-1 rounded-full flex items-center hover:bg-[#F4B400] hover:text-[#1A1F71]">
              <FaUserCircle className="text-xl" />
              <p className="font-semibold ml-2 ">Profile</p>
            </button>
          </div>
        </div>
        <div className="pt-20 ml-20 ">
          <div className="sidebar bg-[#FFF] fixed">
            <Sidebar />
            <hr className="mx-4"></hr>
            <div className="p-4 text-[#333]">
              <Link href="" className="flex items-center space-x-5 py-2">
                <HiPuzzle className="text-xl text-[#333]" />
                <p>Settings and Privacy</p>
              </Link>
              <Link href="" className="flex items-center space-x-5 py-2">
                <IoMdHelpCircle className="text-xl text-[#333]" />
                <p>Help and Center</p>
              </Link>

              <Link href="">
                <p className="mt-4 font-bold text-[#1A1F71]">Log Out</p>
              </Link>

              <div className="text-xs text-center absolute -bottom-10 left-1/2 -translate-x-1/2 w-full text-[#333]">
                <p>CopyRight@Homify.inc</p>
                <p>Designed by Homify team</p>
              </div>
            </div>
          </div>

          <section className="  ml-65 mr-5"> {children}</section>
        </div>
      </body>
    </html>
  );
}
